services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    command: tail -f /dev/null
    volumes:
      - "/home/yago/pipeline-dados/spark/jobs:/opt/spark/jobs"
      - "/home/yago/pipeline-dados/data-lake/bronze:/data/bronze"
      - "/home/yago/pipeline-dados/data-lake/silver:/data/silver"
      - "/home/yago/pipeline-dados/data-lake/gold:/data/gold"
      - "/home/yago/pipeline-dados/data-lake/gold_tmp:/data/gold_tmp"
    ports:
      - "4040:4040"
    networks:
      - pipeline

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    user: root
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      DOCKER_API_VERSION: "1.44"
    ports:
      - "8081:8080"
    volumes:
      - "/home/yago/pipeline-dados/airflow/dags:/opt/airflow/dags"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - pipeline
    depends_on:
      - spark
      - minio
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin123 --firstname Admin --lastname User --role Admin --email admin@local || true &&
        airflow scheduler &
        airflow webserver
      "

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ':9001'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - "/home/yago/pipeline-dados/data-lake:/data"
    networks:
      - pipeline

networks:
  pipeline:
    driver: bridge